FROM nginx:1.25-alpine

ARG ADMIN_REDIRECT_URL=https://www.personalcreativemz.com/painel

RUN printf 'server {\n    listen 80;\n    server_name _;\n    location / {\n        return 301 %s;\n    }\n}\n' \
    "${ADMIN_REDIRECT_URL}" > /etc/nginx/conf.d/default.conf && \
    rm -f /etc/nginx/conf.d/default.conf.template

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
